name: Build Mindustry IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Mindustry
        uses: actions/checkout@v4
        with:
          repository: Anuken/Mindustry
          ref: v159.7

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Compile IPA
        run: ./gradlew ios:createIPA -Probovm.iosSkipSigning=true

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Mindustry-iOS-v159.7
          path: ios/build/robovm/*.ipa
